import type { ConfigValue, ListConfigValuesParams, ListConfigValuesResponse } from "./types";

export const MOCK_CONFIG_VALUES: ConfigValue[] = [
  {
    id: "01HRX0AGENTOAS65MINAGE0001",
    domain: "rule",
    key: "ca-oas.rule.age-65.min_age",
    jurisdiction_id: "ca-oas",
    value: 65,
    value_type: "number",
    effective_from: "2025-01-01T00:00:00Z",
    effective_to: null,
    citation: "OAS Act, s. 3(1)",
    author: "human:minister.seniors",
    approved_by: "human:minister.seniors",
    rationale: "Statutory minimum age for Old Age Security pension.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2024-12-12T10:00:00Z",
  },
  {
    id: "01HRX0AGENTOAS65RESIDENCY02",
    domain: "rule",
    key: "ca-oas.rule.age-65.residency_years",
    jurisdiction_id: "ca-oas",
    value: 10,
    value_type: "number",
    effective_from: "2025-01-01T00:00:00Z",
    effective_to: null,
    citation: "OAS Act, s. 3(2)(a)",
    author: "agent:policy-drafter-v2",
    approved_by: "human:minister.seniors",
    rationale: "Years of Canadian residency required after age 18.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2024-12-12T10:05:00Z",
  },
  {
    id: "01HRX0ENUMOASMARITAL000003",
    domain: "enum",
    key: "ca-oas.enum.marital_status",
    jurisdiction_id: "ca-oas",
    value: ["single", "married", "common-law", "widowed", "divorced"],
    value_type: "list",
    effective_from: "2025-01-01T00:00:00Z",
    effective_to: null,
    citation: null,
    author: "agent:taxonomy-bot",
    approved_by: null,
    rationale: "Permitted marital status values for OAS eligibility forms.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2024-12-12T10:10:00Z",
  },
  {
    id: "01HRX0UICOPYWELCOMEFR00004",
    domain: "ui",
    key: "ca-oas.ui.welcome.heading",
    jurisdiction_id: "ca-oas",
    value: "Bienvenue à la Sécurité de la vieillesse",
    value_type: "string",
    effective_from: "2025-02-15T00:00:00Z",
    effective_to: null,
    citation: null,
    author: "human:editor.fr",
    approved_by: "human:editor.lead",
    rationale: "French heading for the OAS landing page.",
    supersedes: null,
    status: "approved",
    language: "fr",
    created_at: "2025-02-10T14:22:00Z",
  },
  {
    id: "01HRX0PROMPTELIGCHECK00005",
    domain: "prompt",
    key: "global.prompt.eligibility.check",
    jurisdiction_id: null,
    value: "Determine eligibility based on the following inputs and cite each rule.",
    value_type: "prompt",
    effective_from: "2026-01-08T00:00:00Z",
    effective_to: null,
    citation: "Internal: prompt-library/v3",
    author: "agent:prompt-curator",
    approved_by: "human:lead.ai",
    rationale: "Shared eligibility-check system prompt for all jurisdictions.",
    supersedes: null,
    status: "approved",
    language: "en",
    created_at: "2026-01-05T09:00:00Z",
  },
  {
    id: "01HRX0ENGINEROUNDING000006",
    domain: "engine",
    key: "global.engine.rounding.mode",
    jurisdiction_id: null,
    value: "banker",
    value_type: "enum",
    effective_from: "2025-06-01T00:00:00Z",
    effective_to: null,
    citation: "ISO 80000-1:2009",
    author: "human:cto",
    approved_by: "human:cto",
    rationale: "Default rounding mode for monetary calculations.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2025-05-20T11:30:00Z",
  },
  {
    id: "01HRX0RULEUSFEDSSAMINAGE07",
    domain: "rule",
    key: "us-fed.rule.ssa.early_retirement_age",
    jurisdiction_id: "us-fed",
    value: 62,
    value_type: "number",
    effective_from: "2025-01-01T00:00:00Z",
    effective_to: null,
    citation: "42 U.S.C. § 402(q)",
    author: "agent:policy-drafter-v2",
    approved_by: "human:ssa.policy",
    rationale: "Earliest age at which reduced retirement benefits may begin.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2024-11-01T08:00:00Z",
  },
  {
    id: "01HRX0RULEDEBUNDRENTE00008",
    domain: "rule",
    key: "de-bund.rule.rente.regelaltersgrenze",
    jurisdiction_id: "de-bund",
    value: 67,
    value_type: "number",
    effective_from: "2031-01-01T00:00:00Z",
    effective_to: null,
    citation: "SGB VI § 35",
    author: "human:bmas.referat",
    approved_by: "human:bmas.referat",
    rationale: "Regelaltersgrenze in der gesetzlichen Rentenversicherung.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2024-09-15T07:00:00Z",
  },
  {
    id: "01HRX0UIBRFEDIRPFLABEL009",
    domain: "ui",
    key: "br-fed.ui.irpf.deduction.label",
    jurisdiction_id: "br-fed",
    value: "Deduções permitidas",
    value_type: "string",
    effective_from: "2026-03-01T00:00:00Z",
    effective_to: null,
    citation: null,
    author: "agent:i18n-bot",
    approved_by: null,
    rationale: "Portuguese label for allowed IRPF deductions.",
    supersedes: null,
    status: "pending",
    language: "pt",
    created_at: "2026-02-25T12:00:00Z",
  },
  {
    id: "01HRX0RULEUKGOVSTPENS00010",
    domain: "rule",
    key: "uk-gov.rule.state-pension.qualifying_years",
    jurisdiction_id: "uk-gov",
    value: 35,
    value_type: "number",
    effective_from: "2025-04-06T00:00:00Z",
    effective_to: null,
    citation: "Pensions Act 2014, Sch. 1",
    author: "human:dwp.policy",
    approved_by: "human:dwp.policy",
    rationale: "Years of NI contributions required for full new State Pension.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2025-03-30T09:00:00Z",
  },
  // ── Superseded versions, added so the timeline + diff have real history ──
  {
    id: "01HRX0AGENTOAS65MINAGE0000",
    domain: "rule",
    key: "ca-oas.rule.age-65.min_age",
    jurisdiction_id: "ca-oas",
    value: 60,
    value_type: "number",
    effective_from: "2010-01-01T00:00:00Z",
    effective_to: "2024-12-31T23:59:59Z",
    citation: "OAS Act, s. 3(1) (rev. 2009)",
    author: "human:minister.seniors",
    approved_by: "human:minister.seniors",
    rationale: "Original statutory minimum age before the 2024 amendment.",
    supersedes: null,
    status: "approved",
    language: null,
    created_at: "2009-12-01T10:00:00Z",
  },
  {
    id: "01HRX0PROMPTELIGCHECK00004",
    domain: "prompt",
    key: "global.prompt.eligibility.check",
    jurisdiction_id: null,
    value: "Decide eligibility from the inputs. Reference applicable rules.",
    value_type: "prompt",
    effective_from: "2025-06-01T00:00:00Z",
    effective_to: "2026-01-07T23:59:59Z",
    citation: "Internal: prompt-library/v2",
    author: "agent:prompt-curator",
    approved_by: "human:lead.ai",
    rationale: "Earlier eligibility-check prompt; superseded by the citation-aware v3.",
    supersedes: null,
    status: "approved",
    language: "en",
    created_at: "2025-05-25T09:00:00Z",
  },
];

export function filterMockConfigValues(params: ListConfigValuesParams): ListConfigValuesResponse {
  const { domain, key_prefix, jurisdiction_id, language } = params;
  const values = MOCK_CONFIG_VALUES.filter((v) => {
    if (domain && domain !== "all" && v.domain !== domain) return false;
    if (key_prefix && !v.key.toLowerCase().includes(key_prefix.toLowerCase())) return false;
    if (jurisdiction_id && jurisdiction_id !== "all") {
      if (jurisdiction_id === "global" && v.jurisdiction_id !== null) return false;
      if (jurisdiction_id !== "global" && v.jurisdiction_id !== jurisdiction_id) return false;
    }
    if (language && language !== "all" && v.language !== language) return false;
    return true;
  });
  return { values, count: values.length };
}
