/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncodeIndexRouteImport } from './routes/encode.index'
import { Route as ConfigIndexRouteImport } from './routes/config.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as EncodeNewRouteImport } from './routes/encode.new'
import { Route as EncodeBatchIdRouteImport } from './routes/encode.$batchId'
import { Route as ConfigDraftRouteImport } from './routes/config.draft'
import { Route as ConfigDiffRouteImport } from './routes/config.diff'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ConfigPromptsIndexRouteImport } from './routes/config.prompts.index'
import { Route as ConfigApprovalsIndexRouteImport } from './routes/config.approvals.index'
import { Route as ConfigApprovalsIdRouteImport } from './routes/config.approvals.$id'
import { Route as ConfigKeyJurisdictionIdRouteImport } from './routes/config.$key.$jurisdictionId'
import { Route as ConfigPromptsKeyJurisdictionIdEditRouteImport } from './routes/config.prompts.$key.$jurisdictionId.edit'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncodeIndexRoute = EncodeIndexRouteImport.update({
  id: '/encode/',
  path: '/encode/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncodeNewRoute = EncodeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EncodeRoute,
} as any)
const EncodeBatchIdRoute = EncodeBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => EncodeRoute,
} as any)
const ConfigDraftRoute = ConfigDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigDiffRoute = ConfigDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ConfigRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const ConfigPromptsIndexRoute = ConfigPromptsIndexRouteImport.update({
  id: '/config/prompts/',
  path: '/config/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigApprovalsIndexRoute = ConfigApprovalsIndexRouteImport.update({
  id: '/config/approvals/',
  path: '/config/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigApprovalsIdRoute = ConfigApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConfigApprovalsRoute,
} as any)
const ConfigKeyJurisdictionIdRoute = ConfigKeyJurisdictionIdRouteImport.update({
  id: '/$key/$jurisdictionId',
  path: '/$key/$jurisdictionId',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigPromptsKeyJurisdictionIdEditRoute =
  ConfigPromptsKeyJurisdictionIdEditRouteImport.update({
    id: '/$key/$jurisdictionId/edit',
    path: '/$key/$jurisdictionId/edit',
    getParentRoute: () => ConfigPromptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authority': typeof AuthorityRoute
  '/policies': typeof PoliciesRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/encode/$batchId': typeof EncodeBatchIdRoute
  '/encode/new': typeof EncodeNewRoute
  '/cases/': typeof CasesIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/encode/': typeof EncodeIndexRoute
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/approvals/': typeof ConfigApprovalsIndexRoute
  '/config/prompts/': typeof ConfigPromptsIndexRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authority': typeof AuthorityRoute
  '/policies': typeof PoliciesRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/encode/$batchId': typeof EncodeBatchIdRoute
  '/encode/new': typeof EncodeNewRoute
  '/cases': typeof CasesIndexRoute
  '/config': typeof ConfigIndexRoute
  '/encode': typeof EncodeIndexRoute
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/approvals': typeof ConfigApprovalsIndexRoute
  '/config/prompts': typeof ConfigPromptsIndexRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authority': typeof AuthorityRoute
  '/policies': typeof PoliciesRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/encode/$batchId': typeof EncodeBatchIdRoute
  '/encode/new': typeof EncodeNewRoute
  '/cases/': typeof CasesIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/encode/': typeof EncodeIndexRoute
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/approvals/': typeof ConfigApprovalsIndexRoute
  '/config/prompts/': typeof ConfigPromptsIndexRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/authority'
    | '/policies'
    | '/cases/$caseId'
    | '/config/diff'
    | '/config/draft'
    | '/encode/$batchId'
    | '/encode/new'
    | '/cases/'
    | '/config/'
    | '/encode/'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/approvals/'
    | '/config/prompts/'
    | '/config/prompts/$key/$jurisdictionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/authority'
    | '/policies'
    | '/cases/$caseId'
    | '/config/diff'
    | '/config/draft'
    | '/encode/$batchId'
    | '/encode/new'
    | '/cases'
    | '/config'
    | '/encode'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/approvals'
    | '/config/prompts'
    | '/config/prompts/$key/$jurisdictionId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/authority'
    | '/policies'
    | '/cases/$caseId'
    | '/config/diff'
    | '/config/draft'
    | '/encode/$batchId'
    | '/encode/new'
    | '/cases/'
    | '/config/'
    | '/encode/'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/approvals/'
    | '/config/prompts/'
    | '/config/prompts/$key/$jurisdictionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthorityRoute: typeof AuthorityRoute
  PoliciesRoute: typeof PoliciesRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  EncodeIndexRoute: typeof EncodeIndexRoute
  ConfigApprovalsIndexRoute: typeof ConfigApprovalsIndexRoute
  ConfigPromptsIndexRoute: typeof ConfigPromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encode/': {
      id: '/encode/'
      path: '/encode'
      fullPath: '/encode/'
      preLoaderRoute: typeof EncodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encode/new': {
      id: '/encode/new'
      path: '/new'
      fullPath: '/encode/new'
      preLoaderRoute: typeof EncodeNewRouteImport
      parentRoute: typeof EncodeRoute
    }
    '/encode/$batchId': {
      id: '/encode/$batchId'
      path: '/$batchId'
      fullPath: '/encode/$batchId'
      preLoaderRoute: typeof EncodeBatchIdRouteImport
      parentRoute: typeof EncodeRoute
    }
    '/config/draft': {
      id: '/config/draft'
      path: '/draft'
      fullPath: '/config/draft'
      preLoaderRoute: typeof ConfigDraftRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/diff': {
      id: '/config/diff'
      path: '/diff'
      fullPath: '/config/diff'
      preLoaderRoute: typeof ConfigDiffRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/config/prompts/': {
      id: '/config/prompts/'
      path: '/config/prompts'
      fullPath: '/config/prompts/'
      preLoaderRoute: typeof ConfigPromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/approvals/': {
      id: '/config/approvals/'
      path: '/config/approvals'
      fullPath: '/config/approvals/'
      preLoaderRoute: typeof ConfigApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/approvals/$id': {
      id: '/config/approvals/$id'
      path: '/$id'
      fullPath: '/config/approvals/$id'
      preLoaderRoute: typeof ConfigApprovalsIdRouteImport
      parentRoute: typeof ConfigApprovalsRoute
    }
    '/config/$key/$jurisdictionId': {
      id: '/config/$key/$jurisdictionId'
      path: '/$key/$jurisdictionId'
      fullPath: '/config/$key/$jurisdictionId'
      preLoaderRoute: typeof ConfigKeyJurisdictionIdRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/prompts/$key/$jurisdictionId/edit': {
      id: '/config/prompts/$key/$jurisdictionId/edit'
      path: '/$key/$jurisdictionId/edit'
      fullPath: '/config/prompts/$key/$jurisdictionId/edit'
      preLoaderRoute: typeof ConfigPromptsKeyJurisdictionIdEditRouteImport
      parentRoute: typeof ConfigPromptsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthorityRoute: AuthorityRoute,
  PoliciesRoute: PoliciesRoute,
  CasesIndexRoute: CasesIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  EncodeIndexRoute: EncodeIndexRoute,
  ConfigApprovalsIndexRoute: ConfigApprovalsIndexRoute,
  ConfigPromptsIndexRoute: ConfigPromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
