/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigPromptsRouteImport } from './routes/config.prompts'
import { Route as ConfigDraftRouteImport } from './routes/config.draft'
import { Route as ConfigDiffRouteImport } from './routes/config.diff'
import { Route as ConfigApprovalsRouteImport } from './routes/config.approvals'
import { Route as ConfigApprovalsIdRouteImport } from './routes/config.approvals.$id'
import { Route as ConfigKeyJurisdictionIdRouteImport } from './routes/config.$key.$jurisdictionId'
import { Route as ConfigPromptsKeyJurisdictionIdEditRouteImport } from './routes/config.prompts.$key.$jurisdictionId.edit'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigPromptsRoute = ConfigPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigDraftRoute = ConfigDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigDiffRoute = ConfigDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigApprovalsRoute = ConfigApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigApprovalsIdRoute = ConfigApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConfigApprovalsRoute,
} as any)
const ConfigKeyJurisdictionIdRoute = ConfigKeyJurisdictionIdRouteImport.update({
  id: '/$key/$jurisdictionId',
  path: '/$key/$jurisdictionId',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigPromptsKeyJurisdictionIdEditRoute =
  ConfigPromptsKeyJurisdictionIdEditRouteImport.update({
    id: '/$key/$jurisdictionId/edit',
    path: '/$key/$jurisdictionId/edit',
    getParentRoute: () => ConfigPromptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/config/approvals': typeof ConfigApprovalsRouteWithChildren
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/config/prompts': typeof ConfigPromptsRouteWithChildren
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/config/approvals': typeof ConfigApprovalsRouteWithChildren
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/config/prompts': typeof ConfigPromptsRouteWithChildren
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config': typeof ConfigRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/config/approvals': typeof ConfigApprovalsRouteWithChildren
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/config/prompts': typeof ConfigPromptsRouteWithChildren
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/config'
    | '/policies'
    | '/config/approvals'
    | '/config/diff'
    | '/config/draft'
    | '/config/prompts'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/prompts/$key/$jurisdictionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/config'
    | '/policies'
    | '/config/approvals'
    | '/config/diff'
    | '/config/draft'
    | '/config/prompts'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/prompts/$key/$jurisdictionId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/config'
    | '/policies'
    | '/config/approvals'
    | '/config/diff'
    | '/config/draft'
    | '/config/prompts'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/prompts/$key/$jurisdictionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfigRoute: typeof ConfigRouteWithChildren
  PoliciesRoute: typeof PoliciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/prompts': {
      id: '/config/prompts'
      path: '/prompts'
      fullPath: '/config/prompts'
      preLoaderRoute: typeof ConfigPromptsRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/draft': {
      id: '/config/draft'
      path: '/draft'
      fullPath: '/config/draft'
      preLoaderRoute: typeof ConfigDraftRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/diff': {
      id: '/config/diff'
      path: '/diff'
      fullPath: '/config/diff'
      preLoaderRoute: typeof ConfigDiffRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/approvals': {
      id: '/config/approvals'
      path: '/approvals'
      fullPath: '/config/approvals'
      preLoaderRoute: typeof ConfigApprovalsRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/approvals/$id': {
      id: '/config/approvals/$id'
      path: '/$id'
      fullPath: '/config/approvals/$id'
      preLoaderRoute: typeof ConfigApprovalsIdRouteImport
      parentRoute: typeof ConfigApprovalsRoute
    }
    '/config/$key/$jurisdictionId': {
      id: '/config/$key/$jurisdictionId'
      path: '/$key/$jurisdictionId'
      fullPath: '/config/$key/$jurisdictionId'
      preLoaderRoute: typeof ConfigKeyJurisdictionIdRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/prompts/$key/$jurisdictionId/edit': {
      id: '/config/prompts/$key/$jurisdictionId/edit'
      path: '/$key/$jurisdictionId/edit'
      fullPath: '/config/prompts/$key/$jurisdictionId/edit'
      preLoaderRoute: typeof ConfigPromptsKeyJurisdictionIdEditRouteImport
      parentRoute: typeof ConfigPromptsRoute
    }
  }
}

interface ConfigApprovalsRouteChildren {
  ConfigApprovalsIdRoute: typeof ConfigApprovalsIdRoute
}

const ConfigApprovalsRouteChildren: ConfigApprovalsRouteChildren = {
  ConfigApprovalsIdRoute: ConfigApprovalsIdRoute,
}

const ConfigApprovalsRouteWithChildren = ConfigApprovalsRoute._addFileChildren(
  ConfigApprovalsRouteChildren,
)

interface ConfigPromptsRouteChildren {
  ConfigPromptsKeyJurisdictionIdEditRoute: typeof ConfigPromptsKeyJurisdictionIdEditRoute
}

const ConfigPromptsRouteChildren: ConfigPromptsRouteChildren = {
  ConfigPromptsKeyJurisdictionIdEditRoute:
    ConfigPromptsKeyJurisdictionIdEditRoute,
}

const ConfigPromptsRouteWithChildren = ConfigPromptsRoute._addFileChildren(
  ConfigPromptsRouteChildren,
)

interface ConfigRouteChildren {
  ConfigApprovalsRoute: typeof ConfigApprovalsRouteWithChildren
  ConfigDiffRoute: typeof ConfigDiffRoute
  ConfigDraftRoute: typeof ConfigDraftRoute
  ConfigPromptsRoute: typeof ConfigPromptsRouteWithChildren
  ConfigKeyJurisdictionIdRoute: typeof ConfigKeyJurisdictionIdRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigApprovalsRoute: ConfigApprovalsRouteWithChildren,
  ConfigDiffRoute: ConfigDiffRoute,
  ConfigDraftRoute: ConfigDraftRoute,
  ConfigPromptsRoute: ConfigPromptsRouteWithChildren,
  ConfigKeyJurisdictionIdRoute: ConfigKeyJurisdictionIdRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfigRoute: ConfigRouteWithChildren,
  PoliciesRoute: PoliciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
