/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenRouteImport } from './routes/screen'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as EncodeRouteImport } from './routes/encode'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncodeNewRouteImport } from './routes/encode.new'
import { Route as EncodeBatchIdRouteImport } from './routes/encode.$batchId'
import { Route as ConfigPromptsRouteImport } from './routes/config.prompts'
import { Route as ConfigDraftRouteImport } from './routes/config.draft'
import { Route as ConfigDiffRouteImport } from './routes/config.diff'
import { Route as ConfigApprovalsRouteImport } from './routes/config.approvals'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ConfigApprovalsIdRouteImport } from './routes/config.approvals.$id'
import { Route as ConfigKeyJurisdictionIdRouteImport } from './routes/config.$key.$jurisdictionId'
import { Route as ConfigPromptsKeyJurisdictionIdEditRouteImport } from './routes/config.prompts.$key.$jurisdictionId.edit'

const ScreenRoute = ScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const EncodeRoute = EncodeRouteImport.update({
  id: '/encode',
  path: '/encode',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncodeNewRoute = EncodeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EncodeRoute,
} as any)
const EncodeBatchIdRoute = EncodeBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => EncodeRoute,
} as any)
const ConfigPromptsRoute = ConfigPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigDraftRoute = ConfigDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigDiffRoute = ConfigDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigApprovalsRoute = ConfigApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ConfigRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const ConfigApprovalsIdRoute = ConfigApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConfigApprovalsRoute,
} as any)
const ConfigKeyJurisdictionIdRoute = ConfigKeyJurisdictionIdRouteImport.update({
  id: '/$key/$jurisdictionId',
  path: '/$key/$jurisdictionId',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigPromptsKeyJurisdictionIdEditRoute =
  ConfigPromptsKeyJurisdictionIdEditRouteImport.update({
    id: '/$key/$jurisdictionId/edit',
    path: '/$key/$jurisdictionId/edit',
    getParentRoute: () => ConfigPromptsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authority': typeof AuthorityRoute
  '/cases': typeof CasesRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/encode': typeof EncodeRouteWithChildren
  '/impact': typeof ImpactRoute
  '/policies': typeof PoliciesRoute
  '/screen': typeof ScreenRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/config/approvals': typeof ConfigApprovalsRouteWithChildren
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/config/prompts': typeof ConfigPromptsRouteWithChildren
  '/encode/$batchId': typeof EncodeBatchIdRoute
  '/encode/new': typeof EncodeNewRoute
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authority': typeof AuthorityRoute
  '/cases': typeof CasesRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/encode': typeof EncodeRouteWithChildren
  '/impact': typeof ImpactRoute
  '/policies': typeof PoliciesRoute
  '/screen': typeof ScreenRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/config/approvals': typeof ConfigApprovalsRouteWithChildren
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/config/prompts': typeof ConfigPromptsRouteWithChildren
  '/encode/$batchId': typeof EncodeBatchIdRoute
  '/encode/new': typeof EncodeNewRoute
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/authority': typeof AuthorityRoute
  '/cases': typeof CasesRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/encode': typeof EncodeRouteWithChildren
  '/impact': typeof ImpactRoute
  '/policies': typeof PoliciesRoute
  '/screen': typeof ScreenRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/config/approvals': typeof ConfigApprovalsRouteWithChildren
  '/config/diff': typeof ConfigDiffRoute
  '/config/draft': typeof ConfigDraftRoute
  '/config/prompts': typeof ConfigPromptsRouteWithChildren
  '/encode/$batchId': typeof EncodeBatchIdRoute
  '/encode/new': typeof EncodeNewRoute
  '/config/$key/$jurisdictionId': typeof ConfigKeyJurisdictionIdRoute
  '/config/approvals/$id': typeof ConfigApprovalsIdRoute
  '/config/prompts/$key/$jurisdictionId/edit': typeof ConfigPromptsKeyJurisdictionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/authority'
    | '/cases'
    | '/config'
    | '/encode'
    | '/impact'
    | '/policies'
    | '/screen'
    | '/cases/$caseId'
    | '/config/approvals'
    | '/config/diff'
    | '/config/draft'
    | '/config/prompts'
    | '/encode/$batchId'
    | '/encode/new'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/prompts/$key/$jurisdictionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/authority'
    | '/cases'
    | '/config'
    | '/encode'
    | '/impact'
    | '/policies'
    | '/screen'
    | '/cases/$caseId'
    | '/config/approvals'
    | '/config/diff'
    | '/config/draft'
    | '/config/prompts'
    | '/encode/$batchId'
    | '/encode/new'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/prompts/$key/$jurisdictionId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/authority'
    | '/cases'
    | '/config'
    | '/encode'
    | '/impact'
    | '/policies'
    | '/screen'
    | '/cases/$caseId'
    | '/config/approvals'
    | '/config/diff'
    | '/config/draft'
    | '/config/prompts'
    | '/encode/$batchId'
    | '/encode/new'
    | '/config/$key/$jurisdictionId'
    | '/config/approvals/$id'
    | '/config/prompts/$key/$jurisdictionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthorityRoute: typeof AuthorityRoute
  CasesRoute: typeof CasesRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  EncodeRoute: typeof EncodeRouteWithChildren
  ImpactRoute: typeof ImpactRoute
  PoliciesRoute: typeof PoliciesRoute
  ScreenRoute: typeof ScreenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screen': {
      id: '/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof ScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encode': {
      id: '/encode'
      path: '/encode'
      fullPath: '/encode'
      preLoaderRoute: typeof EncodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encode/new': {
      id: '/encode/new'
      path: '/new'
      fullPath: '/encode/new'
      preLoaderRoute: typeof EncodeNewRouteImport
      parentRoute: typeof EncodeRoute
    }
    '/encode/$batchId': {
      id: '/encode/$batchId'
      path: '/$batchId'
      fullPath: '/encode/$batchId'
      preLoaderRoute: typeof EncodeBatchIdRouteImport
      parentRoute: typeof EncodeRoute
    }
    '/config/prompts': {
      id: '/config/prompts'
      path: '/prompts'
      fullPath: '/config/prompts'
      preLoaderRoute: typeof ConfigPromptsRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/draft': {
      id: '/config/draft'
      path: '/draft'
      fullPath: '/config/draft'
      preLoaderRoute: typeof ConfigDraftRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/diff': {
      id: '/config/diff'
      path: '/diff'
      fullPath: '/config/diff'
      preLoaderRoute: typeof ConfigDiffRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/approvals': {
      id: '/config/approvals'
      path: '/approvals'
      fullPath: '/config/approvals'
      preLoaderRoute: typeof ConfigApprovalsRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/config/approvals/$id': {
      id: '/config/approvals/$id'
      path: '/$id'
      fullPath: '/config/approvals/$id'
      preLoaderRoute: typeof ConfigApprovalsIdRouteImport
      parentRoute: typeof ConfigApprovalsRoute
    }
    '/config/$key/$jurisdictionId': {
      id: '/config/$key/$jurisdictionId'
      path: '/$key/$jurisdictionId'
      fullPath: '/config/$key/$jurisdictionId'
      preLoaderRoute: typeof ConfigKeyJurisdictionIdRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/prompts/$key/$jurisdictionId/edit': {
      id: '/config/prompts/$key/$jurisdictionId/edit'
      path: '/$key/$jurisdictionId/edit'
      fullPath: '/config/prompts/$key/$jurisdictionId/edit'
      preLoaderRoute: typeof ConfigPromptsKeyJurisdictionIdEditRouteImport
      parentRoute: typeof ConfigPromptsRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface ConfigApprovalsRouteChildren {
  ConfigApprovalsIdRoute: typeof ConfigApprovalsIdRoute
}

const ConfigApprovalsRouteChildren: ConfigApprovalsRouteChildren = {
  ConfigApprovalsIdRoute: ConfigApprovalsIdRoute,
}

const ConfigApprovalsRouteWithChildren = ConfigApprovalsRoute._addFileChildren(
  ConfigApprovalsRouteChildren,
)

interface ConfigPromptsRouteChildren {
  ConfigPromptsKeyJurisdictionIdEditRoute: typeof ConfigPromptsKeyJurisdictionIdEditRoute
}

const ConfigPromptsRouteChildren: ConfigPromptsRouteChildren = {
  ConfigPromptsKeyJurisdictionIdEditRoute:
    ConfigPromptsKeyJurisdictionIdEditRoute,
}

const ConfigPromptsRouteWithChildren = ConfigPromptsRoute._addFileChildren(
  ConfigPromptsRouteChildren,
)

interface ConfigRouteChildren {
  ConfigApprovalsRoute: typeof ConfigApprovalsRouteWithChildren
  ConfigDiffRoute: typeof ConfigDiffRoute
  ConfigDraftRoute: typeof ConfigDraftRoute
  ConfigPromptsRoute: typeof ConfigPromptsRouteWithChildren
  ConfigKeyJurisdictionIdRoute: typeof ConfigKeyJurisdictionIdRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigApprovalsRoute: ConfigApprovalsRouteWithChildren,
  ConfigDiffRoute: ConfigDiffRoute,
  ConfigDraftRoute: ConfigDraftRoute,
  ConfigPromptsRoute: ConfigPromptsRouteWithChildren,
  ConfigKeyJurisdictionIdRoute: ConfigKeyJurisdictionIdRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface EncodeRouteChildren {
  EncodeBatchIdRoute: typeof EncodeBatchIdRoute
  EncodeNewRoute: typeof EncodeNewRoute
}

const EncodeRouteChildren: EncodeRouteChildren = {
  EncodeBatchIdRoute: EncodeBatchIdRoute,
  EncodeNewRoute: EncodeNewRoute,
}

const EncodeRouteWithChildren =
  EncodeRoute._addFileChildren(EncodeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthorityRoute: AuthorityRoute,
  CasesRoute: CasesRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  EncodeRoute: EncodeRouteWithChildren,
  ImpactRoute: ImpactRoute,
  PoliciesRoute: PoliciesRoute,
  ScreenRoute: ScreenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
